name: Factos Deploy to Server

on:
  push:
    branches:
      - release

#jobs:
#  deploy-to-server:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to the server via SSH
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest
#
##           기존 컨테이너 정지 및 삭제
#            docker stop factos || true
#            docker rm factos || true
#
#            # 새 컨테이너 실행
#            docker run -d \
#              --name factos \
#              -p 80:8080 \
#              -e SPRING_PROFILES_ACTIVE=prod \
#              ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest
#
#            # 72시간 이상된 오래된 이미지 정리
#            docker image prune -a --force --filter "until=72h"
