name: Factos CI/CD Pipeline

on:
  push:
    branches:
      - release

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          submodules: true

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Create resources directory
        run: mkdir -p src/main/resources

      - name: Copy prod yml from submodule to resources
        run: cp config/application-prod.yml src/main/resources/application-prod.yml

      - name: Copy prod.yml from submodule to resources
        run: cp config/application-prod.yml src/main/resources/application-prod.yml

      - name: Build JAR (skip tests)
        run: ./gradlew clean bootJar -x test
        env:
          SPRING_PROFILES_ACTIVE: prod

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set image tag
        id: vars
        run: echo "TAG=$(date +%Y%m%d)-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/factos:${{ env.TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/factos:${{ env.TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest


      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/factos:${{ env.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest

      - name: Deploy to the server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest

            docker stop factos || true
            docker rm factos || true

            docker run -d \
              --name factos \
              -p 80:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              ${{ secrets.DOCKERHUB_USERNAME }}/factos:latest

            docker image prune -a --force --filter "until=72h"